### ISSUE TITLE
error while getting mounts: Error making API request.

### ISSUE THREAD

**Issue by axi92** [xbglowx/vault-kv-search#10]
Hi I get this error:

```
$ vault-kv-search secret/ a
error while getting mounts: Error making API request.

URL: GET https://vault.service.consul:8200/v1/sys/mounts
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

I guess there is a permission to list the mount points, but I dont need that if I know I can access it. Same token as used in the vault UI.
Also the ui gehts the mount point list from this url:
https://vault:8200/v1/sys/internal/ui/mounts

There is it defined: https://github.com/hashicorp/vault/blob/8bf08661646ea7827e59ad8fe7927c53f940e681/api/sys_mounts.go#L21

**Comment by xbglowx** [comment]
Maybe https://github.com/xbglowx/vault-kv-search/pull/32 will fix your problem. You will have to specify the version though, to prevent auto discovery.

**Comment by xbglowx** [comment]
#32 should have fixed this for you.
