### ISSUE TITLE
how to install this tool ?

### ISSUE THREAD

**Issue by yossisht9876** [xbglowx/vault-kv-search#11]
hi 
can i get info how to install this tool
i have a mac 

thanks
@cyrinux @xbglowx

**Comment by cyrinux** [comment]
@yossisht9876 you have to use https://github.com/xbglowx/vault-kv-search/releases/download/v0.1.1/vault-kv-search-0.1.1.darwin-amd64.tar.gz

**Comment by xbglowx** [comment]
Prebuilt binaries for M1 are now part of releases per https://github.com/xbglowx/vault-kv-search/commit/9741829762025deae491243be3fa4ee2748616ae
