### ISSUE TITLE
Can you add aarch64 artifacts ?

### ISSUE THREAD

**Issue by cyrinux** [xbglowx/vault-kv-search#12]
Hi, 

can you please add to your cool vault projects prebuild aarch64/arm cross build binaries next to those for amd64 ?

Thanks you!

**Comment by xbglowx** [comment]
Let me see what I can do.

**Comment by cyrinux** [comment]
Thanks, I will modify archlinux PKGBUILD then to add this/those new architectures.

**Comment by xbglowx** [comment]
I updated 0.1.1 with the new arm64 binaries.

**Comment by cyrinux** [comment]
Yes, it would be neat ! Personally I will use `env GOOS=linux GOARCH=arm64` 😉

**Comment by xbglowx** [comment]
> Yes, it would be neat ! Personally I will use `env GOOS=linux GOARCH=arm64` 😉 Will prepare my PKGBUILD update. The same for vault-kv-mv will be nice too 👍🏻

Right, sorry, you mentioned that in your original request. Let me update the other project as well.

**Comment by xbglowx** [comment]
Done with vault-kv-mv as well.

**Comment by cyrinux** [comment]
Thanks you ! PKGBUILD for archlinux updated.
