### ISSUE TITLE
vault kv v2 not working

### ISSUE THREAD

**Issue by carlos-lehmann** [xbglowx/vault-kv-search#5]
If the backend is v2 (allows versioning compared to v1) vault-kv-search is coming back with following reply:  
`Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv list' for this operation.`
Could you help in getting vault-kv-search working with v2 backends?

Thank you!

**Comment by cyrinux** [comment]
Hi @carlos-lehmann ,

I try to fix this issue in this fork https://github.com/cyrinux/vault-kv-search/

Could you please try and I will open a PR here then ? 

Regards :)
